### ISSUE TITLE
Move repo into organization?

### ISSUE THREAD

**Issue by mhiley** [georust/rust-netcdf#23]
@milesgranger suggested in #22 that we create an org for this repo or find another org willing to take ownership of it. I'm in support of this - my time is limited and I haven't been keeping up with Rust since I wrote the original version of this crate in 2015. 

Any suggestions or opinions on the details here? 
* Where exactly should we move it?
* Who wants to take on a maintainer role?

**Comment by milesgranger** [comment]
I've reached out to [Unidata](https://github.com/Unidata) on the off chance they may be interested, as it seems the best choice. I'll let you know what I hear back.

**Comment by mhiley** [comment]
@julienchastang Greetings (not sure if you remember me from my McIDAS-V days! Hope you are doing well)! Back in 2015 I wrote the initial version of these NetCDF bindings for Rust as a hobby project to learn Rust, and in the following years several folks here on Github have done really good work to add features and make things more robust. I don't have much time these days to act as maintainer so we (the users of this repo) are looking for some direction on how to hand off ownership in a way that makes sense.

Do you have any sense of who at Unidata might have an opinion or some interest in helping with this?

**Comment by milesgranger** [comment]
Per @WardF:
> I'd love to discuss this more, but the netCDF team at Unidata has very limited bandwidth currently, and Rust is not a language we have any experience with.   I'll be happy to take a look at the bindings, and happy to be a part of any discussion regarding the future of the bindings, but without additional community support I'm not sure how much support Unidata can provide in the near future.  
>
> That said, there is precedent for Unidata providing support for netCDF language bindings without taking ownership of them, i.e. netcdf4-python.  
>
>So, as I mentioned, I will take a look at the bindings and I'll raise this question internally. 

I think if it works out here, Unidata is the natural place for it, but [GeoRust](https://github.com/georust) also seems like a good alternative?

**Comment by lwandrebeck** [comment]
Hello,

If Magnus agrees with that, I'd say he's the best to take over maintainership. He's probably the one who dive deeply and recently into the code and thus knows it well.

My knowledge of rust and netcdf is pretty limited, my time too, but I can try to give a bit of help if needed.

I'd love to be able to propose rust at work (scientific image processing), but without correct support from libs such as netcdf, numpy-like and such, it's a no-go.

Best,

**Comment by magnusuMET** [comment]
I'd be happy to take on the role of maintainer in my spare time!

Which organisation is the most appropriate for this crate I am not sure about. A search for "netcdf language:Rust" on github does not reveal any obvious candidates.

**Comment by frewsxcv** [comment]
Happy to add this to the GeoRust org, and add folks to the org, though I don't personally have much bandwidth to help with maintaining. Let me know if yall are interested and I can help with the transfer 👋

**Comment by milesgranger** [comment]
I'm _super_ impressed with @magnusuMET work, along with @mhiley and everyone else. 

IMO, I would rather see this go into an organization as it presents at least two benefits:

1. People _eventually_ move on to something else, through no fault of their own, and maintenance slows/stops. Under and organization this is at least mitigated to an extent as people filter in and out of the org.
2. It is an easier sell in a work environment to include such a lib in a project maintained by an org, rather than when the project is under "some guy on github". 

Cool that this could be included in GeoRust, and we can share the workload there. :world_map: I'm all for it, and remain happy however it continues, in some way, to be maintained. :clap:

**Comment by julienchastang** [comment]
Just responding to the [earlier comment](https://github.com/mhiley/rust-netcdf/issues/23#issuecomment-541096700). Unfortunately, I don't have any good suggestions other than pinging those that are already on this thread (e.g., @WardF and @DennisHeimbigner).

**Comment by magnusuMET** [comment]
@mhiley Would you like to give me collaborator status on this repository? I have some time this weekend to add some features that I've missed, especially reading string variables.

**Comment by mhiley** [comment]
@magnusuMET just sent you a collaborator invite. Let me know if you haven't gotten it. Also, did you ever get an invite from crates.io? The "Manage Crate Owners" page there is showing you as an owner on `netcdf` but not `netcdf-sys`. I just tried to re-invite you to `netcdf-sys`.

Sounds like we've converged on moving this repo to the GeoRust org, unless there are any objections. Looks to me like the right place for it. @frewsxcv are you ready for me to go ahead and do that? Is it as simple as following the instructions [here](https://help.github.com/en/articles/transferring-a-repository)? Anything else I need to take care of?

**Comment by magnusuMET** [comment]
Thanks @mhiley! The invite for `netcdf` was available when I signed up on crates.io, but for `netcdf-sys` the invite only appeared just now.

**Comment by lwandrebeck** [comment]
It looks like none is against getting under the umbrella of GeoRust. @magnusuMET , can you take care of the transfer with @frewsxcv ?
Thx !

**Comment by magnusuMET** [comment]
The transfer has to be done by the owner of the repo. @frewsxcv, could you allow @mhiley to create a repository in GeoRust? Then @mhiley should be able to do the transfer by following the instructions above.

**Comment by frewsxcv** [comment]
@mhiley Just sent you an invite to the GeoRust org. Let me know if you need any help with the transfer 👋

**Comment by milesgranger** [comment]
@mhiley any updates with the move? Know you're a busy person. :slightly_smiling_face:

**Comment by mhiley** [comment]
@milesgranger Thanks for the reminder - I'll get to it this week.

**Comment by magnusuMET** [comment]
@mhiley Just a friendly reminder (:

**Comment by mhiley** [comment]
@magnusuMET attempt to transfer repo happening in a moment 😃

**Comment by mhiley** [comment]
@frewsxcv @magnusuMET @milesgranger transfer complete, looks like it worked! Sorry for the delay. Let me know if there's anything else I can do!

**Comment by frewsxcv** [comment]
@mhiley Yep, looks good, thanks! Only other thing left is giving GeoRust members permission to publish the crates. Can you run `cargo owner -a github:georust:core` in the root directory and the `rust-netcdf` directory?

**Comment by magnusuMET** [comment]
@frewsxcv I am also an owner of the crate. Running the command gives me
```
error: failed to invite owners to crate netcdf: api errors (status 200 OK): could not find the github team georust/core
```
Am I doing something wrong?

**Comment by frewsxcv** [comment]
@magnusuMET woops, i meant to invite you to the org. but i accidentally invited you as an outside collaborator. can you accept the invite in your email and then retry the `cargo owner` command?

**Comment by magnusuMET** [comment]
@frewsxcv And now it worked! Thanks so much for your help!
